version: '3.5'
services:
  server-p5:
    build: ../P5/
    container_name: p5
    volumes:
      - ../P5/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
  server-p6:
    build: ./
    container_name: p6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"
    restart: unless-stopped
    depends_on:
      - server-p5